spring:
  boot:
    admin:
      client:
        metadata:
          user:
            name: ${security.user.name}
            password: ${security.user.password}
      monitor:
        period: 60000
      discovery:
        enabled: true
      notify:
        mail:
          to: xxxxxxxx@163.com
          from: paascloudTest@163.com
      turbine:
        clusters: default
        location: paascloud-monitor
      routes:
        endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream

security:
  user:
    name: admin
    password: admin
  basic:
    enabled: false

turbine:
  app-config: paascloud-gateway #收集监控信息的服务名
  combine-host-port: true
  cluster-name-expression: new String('default') #集群名称